greyblake/nutype

- .github/workflows/ci.yml
- CHANGELOG.md
- Cargo.lock
- Makefile
- README.md
- WORKLOG.md
- dummy/Cargo.toml
- dummy/src/main.rs
- nutype/Cargo.toml
- nutype/src/lib.rs
- nutype_macros/Cargo.toml
- nutype_macros/src/common/models.rs
- nutype_macros/src/common/parse/mod.rs
- nutype_macros/src/float/gen/traits.rs
- nutype_macros/src/float/models.rs
- nutype_macros/src/float/validate.rs
- nutype_macros/src/integer/gen/traits.rs
- nutype_macros/src/integer/models.rs
- nutype_macros/src/integer/validate.rs
- nutype_macros/src/string/gen/traits.rs
- nutype_macros/src/string/models.rs
- nutype_macros/src/string/validate.rs
- test_suite/Cargo.toml
- test_suite/tests/float.rs
- test_suite/tests/integer.rs
- test_suite/tests/string.rs
- test_suite/tests/ui/common/schemars08.rs
- test_suite/tests/ui/common/schemars08.stderr
It addresses #12 
* Add `schemars08` feature flag
* Support derive of `JsonSchema` for integers, floats and strings
> Add basic support to derive schemars::JsonSchema

- nutype_macros/src/common/models.rs
- nutype_macros/src/common/parse/meta.rs
- nutype_macros/src/common/parse/mod.rs
- nutype_macros/src/common/validate.rs
- nutype_macros/src/float/mod.rs
- nutype_macros/src/float/parse.rs
- nutype_macros/src/float/validate.rs
- nutype_macros/src/integer/mod.rs
- nutype_macros/src/integer/parse.rs
- nutype_macros/src/integer/validate.rs
- nutype_macros/src/lib.rs
- nutype_macros/src/string/mod.rs
- nutype_macros/src/string/parse.rs
- nutype_macros/src/string/validate.rs
This enables usage of `darling` for macro attributes parsing.
> Use darling::Error instead of syn::Error

- dummy/src/main.rs
- nutype_macros/src/common/parse/mod.rs
- nutype_macros/src/string/gen/mod.rs
- nutype_macros/src/string/models.rs
- nutype_macros/src/string/parse.rs
- nutype_macros/src/string/validate.rs
- test_suite/tests/string.rs
- test_suite/tests/ui/string/sanitize/multiple_unknown.rs
- test_suite/tests/ui/string/sanitize/multiple_unknown.stderr
- test_suite/tests/ui/string/sanitize/unknown.stderr
- test_suite/tests/ui/string/validate/duplicated.stderr
- test_suite/tests/ui/string/validate/min_len_vs_max_len.stderr
- test_suite/tests/ui/string/validate/unknown.stderr
This is the first baby-step towards using darling to parse `nutype` attributes.
Here we define functions `parse_sanitize_attrs` and `parse_validate_attrs` for String  in terms of `darling`.
> Darling string

- nutype_macros/src/common/parse/mod.rs
- nutype_macros/src/float/mod.rs
- nutype_macros/src/float/parse.rs
- nutype_macros/src/integer/parse.rs
- nutype_macros/src/string/parse.rs
- test_suite/tests/float.rs
- test_suite/tests/ui/float/sanitize/duplicated.stderr
- test_suite/tests/ui/float/validate/duplicated.stderr
- test_suite/tests/ui/float/validate/min_vs_max.stderr
- test_suite/tests/ui/float/validate/unknown.stderr
Addresses #61 . Right now tests are not fixed yet. parse_number with Literal constraint didn't allow for an easy integer -> float conversion. While `parse::<f64>()` irom a string with an integer in it is straightforward, `LitInt` and `LitFloat` didn't enter the picture quite so smoothly hence why I opted for `Lit` enum pattern match, removing the need for Literal in the process.
> Refactor syn parse float

- CHANGELOG.md
- nutype/src/lib.rs
- nutype_macros/src/string/gen/error.rs
- nutype_macros/src/string/gen/mod.rs
- nutype_macros/src/string/models.rs
- nutype_macros/src/string/parse.rs
- nutype_macros/src/string/validate.rs
- test_suite/tests/string.rs
- test_suite/tests/ui/common/attribute_with_wrong_case.rs
- test_suite/tests/ui/common/attribute_with_wrong_case.stderr
- test_suite/tests/ui/string/validate/char_len_min_vs_char_len_max.rs
- test_suite/tests/ui/string/validate/char_len_min_vs_char_len_max.stderr
- test_suite/tests/ui/string/validate/duplicated.rs
- test_suite/tests/ui/string/validate/duplicated.stderr
- test_suite/tests/ui/string/validate/min_len_vs_max_len.stderr
- test_suite/tests/ui/string/validate/unknown.stderr
It addresses https://github.com/greyblake/nutype/issues/51 
Rename string validators
*  `max_len` -> `char_len_max`
*  `min_len` -> `char_len_min`
> Rename max_len -> char_len_max; min_len -> char_len_min

- CHANGELOG.md
- dummy/src/main.rs
- nutype/src/lib.rs
- nutype_macros/src/float/gen/error.rs
- nutype_macros/src/float/gen/mod.rs
- nutype_macros/src/integer/gen/error.rs
- nutype_macros/src/integer/gen/mod.rs
- nutype_macros/src/string/gen/error.rs
- nutype_macros/src/string/gen/mod.rs
- test_suite/tests/float.rs
- test_suite/tests/integer.rs
- test_suite/tests/string.rs
This fixes https://github.com/greyblake/nutype/issues/82
Rename error variants to follow the following formular: `<ValidationRule>Violated`. This implies the following renames:
* `TooShort` -> `CharLenMinViolated`
* `TooLong` -> `CharLenMaxViolated`
* `Empty` -> `NotEmptyViolated`
* `RegexMismatch` -> `RegexViolated`
* `Invalid` -> `PredicateViolated`
* `TooBig` -> `MaxViolated`
* `TooSmall` -> `MinViolated`
* `NotFinite` -> `FiniteViolated`
> Rename error variants to have Violated postfix

- nutype_macros/src/lib.rs
Fixes https://github.com/greyblake/nutype/issues/85
> Add docs on nutype macro

- .github/workflows/ci.yml
- Justfile
- examples/float_sortable/src/main.rs
Fixes https://github.com/greyblake/nutype/issues/114
> Setup typos

- nutype_macros/src/any/gen/error.rs
- nutype_macros/src/float/gen/error.rs
- nutype_macros/src/integer/gen/error.rs
- nutype_macros/src/string/gen/error.rs
This PR is aimed to rewrite the pretty print for vaildator error types to include details about the bounds and the name of a newtype, addressing #105
> initial error message reformat

- CHANGELOG.md
- examples/serde_complex/src/main.rs
- nutype_macros/src/common/gen/traits.rs
- test_suite/tests/any.rs
- test_suite/tests/float.rs
- test_suite/tests/integer.rs
- test_suite/tests/string.rs
- test_suite/tests/ui/float/visibility/private.stderr
- test_suite/tests/ui/float/visibility/private_error.stderr
- test_suite/tests/ui/integer/visibility/private.stderr
- test_suite/tests/ui/integer/visibility/private_error.stderr
- test_suite/tests/ui/string/visibility/private.stderr
- test_suite/tests/ui/string/visibility/private_error.stderr
Followup for https://github.com/greyblake/nutype/pull/125
> Fix serde_complex example

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- dummy/src/main.rs
- examples/any_generics/Cargo.toml
- examples/any_generics/src/main.rs
- nutype_macros/src/any/gen/mod.rs
- nutype_macros/src/any/gen/traits/mod.rs
- nutype_macros/src/common/gen/mod.rs
- nutype_macros/src/common/gen/traits.rs
- nutype_macros/src/common/models.rs
- nutype_macros/src/common/parse/meta.rs
- nutype_macros/src/float/gen/mod.rs
- nutype_macros/src/float/gen/traits/mod.rs
- nutype_macros/src/integer/gen/mod.rs
- nutype_macros/src/integer/gen/traits/mod.rs
- nutype_macros/src/string/gen/mod.rs
- nutype_macros/src/string/gen/traits/mod.rs
- test_suite/tests/any.rs
This is still work in progress.
It's supposed to address https://github.com/greyblake/nutype/issues/133 and https://github.com/greyblake/nutype/issues/130
```rs
#[nutype(
derive(Debug),
validate(predicate = |s| s.len() >= 3),
)]
struct Clarabelle<'b>(Cow<'b, str>);
```
```rs
#[nutype(
derive(Debug),
validate(predicate = |s| s.len() >= 3),
)]
struct Clarabelle<'a>(Cow<'a, str>);
```
```rs
#[nutype(
sanitize(with = |v| { v.sort(); v }),
derive(Debug)
)]
struct SortedVec<T: Ord>(Vec<T>)
```
NOTE: this will be handled in a separate story: https://github.com/greyblake/nutype/issues/142
> Support for generic types

- nutype_macros/src/common/gen/traits.rs
- nutype_macros/src/float/models.rs
- nutype_macros/src/integer/models.rs
Hi! Thanks for this useful software.
This pull request addresses a compilation error that occurs when using the crate with a custom Result type alias and deriving certain traits such as `Deserialize` from `serde`. For example:
```rust
#[nutype(derive(Deserialize))]
struct Name(String);
struct MyError;
pub type Result<T> = std::result::Result<T, MyError>;
```
The error message was:
```
type alias takes 1 generic argument but 2 generic arguments were supplied
expected 1 generic argument
```
- Updated macros to use the absolute path (e.g. `::core::result::Result`) for Result.
Thanks!
> Use absolute path for Result in macro-generated code

- dummy/src/main.rs
- nutype_macros/src/common/gen/traits.rs
- test_suite/tests/any.rs
Fixes https://github.com/greyblake/nutype/issues/157 and https://github.com/greyblake/nutype/issues/156
> Fix derive as ref with generic boundaries

- README.md
- dummy/src/main.rs
- nutype/src/lib.rs
Fixes https://github.com/greyblake/nutype/issues/154
> Add an example with generics in README and lib.rs doc

- dummy/src/main.rs
- nutype_macros/src/common/gen/mod.rs
- nutype_macros/src/common/models.rs
- nutype_macros/src/common/validate.rs
- nutype_macros/src/float/gen/traits/arbitrary.rs
- nutype_macros/src/float/validate.rs
- nutype_macros/src/integer/gen/traits/arbitrary.rs
- nutype_macros/src/string/gen/traits/arbitrary.rs
- nutype_macros/src/string/models.rs
Another step towards https://github.com/greyblake/nutype/issues/161
> Introduce Validation enum

- nutype_macros/src/common/parse/mod.rs
Fixes https://github.com/greyblake/nutype/issues/172
> Improve error message when regex feature is not enabled

- CHANGELOG.md
- nutype_macros/src/any/gen/error.rs
- nutype_macros/src/any/gen/mod.rs
- nutype_macros/src/any/gen/traits/mod.rs
- nutype_macros/src/common/gen/error.rs
- nutype_macros/src/common/gen/mod.rs
- nutype_macros/src/common/gen/parse_error.rs
- nutype_macros/src/common/gen/traits.rs
- nutype_macros/src/common/models.rs
- nutype_macros/src/common/models/error_type_path.rs
- nutype_macros/src/common/parse/mod.rs
- nutype_macros/src/common/validate.rs
- nutype_macros/src/float/gen/error.rs
- nutype_macros/src/float/gen/mod.rs
- nutype_macros/src/float/gen/traits/mod.rs
- nutype_macros/src/integer/gen/error.rs
- nutype_macros/src/integer/gen/mod.rs
- nutype_macros/src/integer/gen/traits/arbitrary.rs
- nutype_macros/src/integer/gen/traits/mod.rs
- nutype_macros/src/string/gen/error.rs
- nutype_macros/src/string/gen/mod.rs
- nutype_macros/src/string/gen/traits/mod.rs
- test_suite/tests/any.rs
Fixes https://github.com/greyblake/nutype/issues/186
> Error path

- nutype_macros/src/common/gen/mod.rs
rust analyzer in VSCode complains about generated tests not being inside a `#[cfg(test)]` module, this PR fixes that.
> add `tests` module around generated tests

- nutype_macros/src/common/gen/mod.rs
rust analyzer in VSCode complains about generated nutype module not being proper snake case, this PR fixes that with a naive to_lower_case call as I think nobody really cares about how exactly it is named except clippy x).
> make `__nutype_{type_name}__` compatible with clippy lint

- .cargo/config.toml
- examples/any_generics/src/main.rs
- nutype_macros/src/any/models.rs
- nutype_macros/src/common/gen/mod.rs
- nutype_macros/src/common/gen/traits.rs
- nutype_macros/src/common/models.rs
- nutype_macros/src/common/parse/mod.rs
- nutype_macros/src/float/mod.rs
- nutype_macros/src/float/models.rs
- nutype_macros/src/float/parse.rs
- nutype_macros/src/integer/mod.rs
- nutype_macros/src/integer/models.rs
- nutype_macros/src/integer/parse.rs
- test_suite/src/test_helpers.rs
- test_suite/tests/any.rs
- test_suite/tests/float.rs
- test_suite/tests/integer.rs
- test_suite/tests/string.rs
Fixes #182 
Also add some config so its hopefully less likely to happen 🙃.
> Fix std instead of core or alloc

- Cargo.lock
- nutype_macros/Cargo.toml
- nutype_macros/build.rs
- nutype_macros/src/common/gen/error.rs
- nutype_macros/src/common/gen/parse_error.rs
rust 1.81.0 made `std::error::Error` available in core.
Users with that version or higher should be getting the `Error` impl no matter if `std` feature is enabled.
fixes #179 without introducing a breaking change
> allow implementing `core::error::Error` when available

- nutype_macros/src/common/gen/traits.rs
Hi!
First of all, thank you for this cool crate.
Recently I have worked on implementing support for the `borsh` crate to make it possible to derive its traits using `nutype`.
While working on it, I encountered the error that it is impossible to derive both `serde` and `borsh` traits.
This was because I used instance methods, and there was a conflict of `serialize` method implementations.
I solved this using the original trait method, and now everything works fine.
This little change is supposed to avoid such problems in future features.
Also, this will improve code consistency because such an approach is already used in the `Deserialize` trait implementation.
```rs
::serde::de::Deserializer::deserialize_newtype_struct(
deserializer,
#type_name_str,
__Visitor {
marker: Default::default(), …
```
> refactor: call the trait method instead of the instance method

- CHANGELOG.md
- dummy/src/main.rs
- nutype_macros/src/any/gen/traits/into_iter.rs
- nutype_macros/src/any/gen/traits/mod.rs
- nutype_macros/src/any/models.rs
- nutype_macros/src/any/validate.rs
- nutype_macros/src/common/models.rs
- nutype_macros/src/common/parse/derive_trait.rs
- nutype_macros/src/float/validate.rs
- nutype_macros/src/integer/validate.rs
- nutype_macros/src/string/validate.rs
- test_suite/tests/any.rs
Implement support for `derive(IntoIterator)`, which essentially generate `IntoIterator` implementation for `Type` and `&Type`.
Addresses https://github.com/greyblake/nutype/issues/203
> Support derive(IntoIterator)

- CHANGELOG.md
- dummy/src/main.rs
- nutype_macros/src/string/generate/error.rs
Fixes https://github.com/greyblake/nutype/issues/215
> Improve error messages for `len_char_max` and `len_char_min` validators.
