- Cargo.lock
- README.md
- nutype/Cargo.toml
- nutype/src/lib.rs
- nutype_macros/Cargo.toml
- nutype_macros/src/string/gen/error.rs
- nutype_macros/src/string/gen/mod.rs
- nutype_macros/src/string/models.rs
- nutype_macros/src/string/parse.rs
- test_suite/tests/float.rs
- test_suite/tests/string.rs
- test_suite/tests/ui/string/derive/from.rs
- test_suite/tests/ui/string/visibility/private_error.rs
- test_suite/tests/ui/string/visibility/private_error.stderr
Thanks for making this library, it's really cool!
Fixes https://github.com/greyblake/nutype/issues/6, along with some minor issues:
- Lint warnings
- Minor spelling mistake
> Updates `present` -> `not_empty`

- .github/workflows/ci.yml
- Makefile
- README.md
- WORKLOG.md
- dummy/Cargo.toml
- dummy/src/main.rs
- nutype/Cargo.toml
- nutype/src/lib.rs
- nutype_macros/Cargo.toml
- nutype_macros/src/common/gen/mod.rs
- nutype_macros/src/common/gen/new_unchecked.rs
- nutype_macros/src/common/models.rs
- nutype_macros/src/common/parse/mod.rs
- nutype_macros/src/float/gen/mod.rs
- nutype_macros/src/float/parse.rs
- nutype_macros/src/integer/gen/mod.rs
- nutype_macros/src/integer/parse.rs
- nutype_macros/src/lib.rs
- nutype_macros/src/string/gen/mod.rs
- nutype_macros/src/string/parse.rs
- test_suite/Cargo.toml
- test_suite/tests/float.rs
- test_suite/tests/integer.rs
- test_suite/tests/string.rs
- test_suite/tests/ui/common/new_unchecked.rs
- test_suite/tests/ui/common/new_unchecked.stderr
> Add new_unchecked feature

- WORKLOG.md
- nutype_macros/src/common/gen/mod.rs
- nutype_macros/src/float/gen/mod.rs
- nutype_macros/src/integer/gen/mod.rs
- nutype_macros/src/string/gen/mod.rs
> Reuse impl_gen_into_inner()

- nutype_macros/src/common/gen/error.rs
- nutype_macros/src/common/gen/mod.rs
- nutype_macros/src/common/gen/parse_error.rs
- nutype_macros/src/common/models.rs
Fix https://github.com/greyblake/nutype/issues/29
> Format ident

- GLOSSARY.md
- nutype_macros/src/common/gen/traits.rs
- nutype_macros/src/float/gen/mod.rs
- nutype_macros/src/float/gen/traits.rs
- nutype_macros/src/integer/gen/mod.rs
- nutype_macros/src/integer/gen/traits.rs
- nutype_macros/src/string/gen/mod.rs
- nutype_macros/src/string/gen/traits.rs
addresses https://github.com/greyblake/nutype/issues/22
> Rename StandardTrait -> TransparentTrait

- CHANGELOG.md
- README.md
- nutype/src/lib.rs
- nutype_macros/src/float/gen/error.rs
- nutype_macros/src/float/gen/mod.rs
- nutype_macros/src/float/models.rs
- nutype_macros/src/float/parse.rs
- test_suite/tests/float.rs
Fix https://github.com/greyblake/nutype/issues/27
> Implement finite validation for float types

- CHANGELOG.md
- Cargo.toml
- nutype_macros/src/common/gen/traits.rs
- nutype_macros/src/float/gen/traits.rs
- nutype_macros/src/float/validate.rs
- nutype_macros/src/integer/gen/traits.rs
- nutype_macros/src/integer/validate.rs
- nutype_macros/src/string/gen/traits.rs
- nutype_macros/src/string/validate.rs
- test_suite/tests/float.rs
- test_suite/tests/integer.rs
- test_suite/tests/string.rs
- test_suite/tests/ui/string/derive/try_from.rs
- test_suite/tests/ui/string/derive/try_from.stderr
Fixes https://github.com/greyblake/nutype/issues/34
> Support TryFrom for types without validation

- nutype_macros/src/common/gen/traits.rs
- nutype_macros/src/common/parse/mod.rs
- nutype_macros/src/lib.rs
- nutype_macros/src/string/parse.rs
- nutype_macros/src/utils.rs
Fixes https://github.com/greyblake/nutype/issues/40
```rs
let msg = match_feature!("foo",
on => "Foo is on!",
off => "Foo is off",
);
```
> Introduce and use match_feature macro

- CHANGELOG.md
- Cargo.lock
- README.md
- nutype/src/lib.rs
- nutype_macros/src/common/gen/traits.rs
- nutype_macros/src/common/models.rs
- nutype_macros/src/common/parse/mod.rs
- nutype_macros/src/float/gen/traits.rs
- nutype_macros/src/float/models.rs
- nutype_macros/src/float/validate.rs
- nutype_macros/src/integer/gen/traits.rs
- nutype_macros/src/integer/models.rs
- nutype_macros/src/integer/validate.rs
- nutype_macros/src/string/gen/traits.rs
- nutype_macros/src/string/models.rs
- nutype_macros/src/string/validate.rs
- test_suite/tests/float.rs
- test_suite/tests/integer.rs
- test_suite/tests/string.rs
Fixes https://github.com/greyblake/nutype/issues/45
> Support derive(Deref)

- nutype_macros/src/common/models.rs
- nutype_macros/src/float/gen/mod.rs
- nutype_macros/src/float/gen/traits.rs
- nutype_macros/src/float/parse.rs
- nutype_macros/src/integer/gen/mod.rs
- nutype_macros/src/integer/gen/traits.rs
- nutype_macros/src/integer/parse.rs
- nutype_macros/src/string/gen/mod.rs
- nutype_macros/src/string/gen/traits.rs
- nutype_macros/src/string/parse.rs
It fixes https://github.com/greyblake/nutype/issues/71
> Use syn::Expr for defualt attribute

- CHANGELOG.md
- nutype/src/lib.rs
- nutype_macros/src/float/gen/error.rs
- nutype_macros/src/float/gen/mod.rs
- nutype_macros/src/float/models.rs
- nutype_macros/src/float/parse.rs
- nutype_macros/src/integer/gen/error.rs
- nutype_macros/src/integer/gen/mod.rs
- nutype_macros/src/integer/models.rs
- nutype_macros/src/integer/parse.rs
- nutype_macros/src/string/gen/error.rs
- nutype_macros/src/string/gen/mod.rs
- nutype_macros/src/string/models.rs
- nutype_macros/src/string/parse.rs
- test_suite/tests/float.rs
- test_suite/tests/integer.rs
- test_suite/tests/string.rs
- test_suite/tests/ui/float/validate/deprecated_with.rs
- test_suite/tests/ui/float/validate/deprecated_with.stderr
> rename with validator to predicate. addresses #70

- Cargo.lock
- README.md
- dummy/src/main.rs
- nutype/Cargo.toml
- nutype/src/lib.rs
- nutype_macros/Cargo.toml
- nutype_macros/src/common/gen/mod.rs
Fixes https://github.com/greyblake/nutype/issues/93
> Infer type for mut callback

- CHANGELOG.md
- examples/serde_complex/src/main.rs
- examples/string_regex_email/src/main.rs
- nutype/src/lib.rs
- nutype_macros/src/string/gen/error.rs
- nutype_macros/src/string/gen/mod.rs
- nutype_macros/src/string/models.rs
- nutype_macros/src/string/parse.rs
- nutype_macros/src/string/validate.rs
- test_suite/tests/string.rs
- test_suite/tests/ui/common/attribute_with_wrong_case.rs
- test_suite/tests/ui/common/attribute_with_wrong_case.stderr
- test_suite/tests/ui/string/validate/char_len_min_vs_char_len_max.stderr
- test_suite/tests/ui/string/validate/duplicated.rs
- test_suite/tests/ui/string/validate/duplicated.stderr
- test_suite/tests/ui/string/validate/len_char_min_vs_len_char_max.rs
- test_suite/tests/ui/string/validate/len_char_min_vs_len_char_max.stderr
- test_suite/tests/ui/string/validate/unknown.stderr
fixes https://github.com/greyblake/nutype/issues/98
> Rename char_len_max -> len_char_max, char_len_min -> len_char_min

- CHANGELOG.md
- Cargo.lock
- Justfile
- WORKLOG.md
- dummy/src/main.rs
- examples/string_bounded_len/Cargo.toml
- examples/string_bounded_len/src/main.rs
- nutype_macros/Cargo.toml
- nutype_macros/src/any/gen/mod.rs
- nutype_macros/src/common/gen/mod.rs
- nutype_macros/src/common/gen/tests.rs
- nutype_macros/src/common/gen/traits.rs
- nutype_macros/src/common/models.rs
- nutype_macros/src/common/parse/mod.rs
- nutype_macros/src/float/gen/mod.rs
- nutype_macros/src/float/models.rs
- nutype_macros/src/float/parse.rs
- nutype_macros/src/integer/gen/mod.rs
- nutype_macros/src/integer/models.rs
- nutype_macros/src/integer/parse.rs
- nutype_macros/src/string/gen/mod.rs
- nutype_macros/src/string/gen/tests.rs
- nutype_macros/src/string/models.rs
- nutype_macros/src/string/parse.rs
- nutype_macros/src/string/validate.rs
- test_suite/tests/float.rs
- test_suite/tests/integer.rs
- test_suite/tests/string.rs
Fixes https://github.com/greyblake/nutype/issues/47
> Const values

- README.md
- WORKLOG.md
- nutype/src/lib.rs
- nutype_macros/src/any/gen/traits.rs
- nutype_macros/src/any/parse.rs
- nutype_macros/src/common/gen/traits.rs
- nutype_macros/src/common/models.rs
- nutype_macros/src/float/gen/traits.rs
- nutype_macros/src/integer/gen/traits/mod.rs
- nutype_macros/src/string/gen/traits.rs
- test_suite/tests/string.rs
Great crate! (pun intended)
This PR fixes some typos...
> Слава Україні!

- CHANGELOG.md
- Cargo.lock
- examples/float_arbitrary/Cargo.toml
- examples/float_arbitrary/src/main.rs
- nutype_macros/src/common/validate.rs
- nutype_macros/src/float/gen/mod.rs
- nutype_macros/src/float/gen/traits/arbitrary.rs
- nutype_macros/src/float/gen/traits/mod.rs
- nutype_macros/src/float/models.rs
- nutype_macros/src/float/validate.rs
- nutype_macros/src/integer/gen/traits/arbitrary.rs
- nutype_macros/src/integer/models.rs
Addresses https://github.com/greyblake/nutype/issues/109
> Arbitrary support for float types

- CHANGELOG.md
- nutype_macros/src/common/gen/mod.rs
- nutype_macros/src/common/gen/traits.rs
- nutype_macros/src/string/gen/traits.rs
Fixes https://github.com/greyblake/nutype/issues/115
> Use #[inline] attr for trivial functions

- Cargo.lock
- examples/no_std_example/Cargo.lock
- nutype_macros/src/float/models.rs
- nutype_macros/src/integer/models.rs
> Remove dead code

- examples/any_generics/src/main.rs
- nutype_macros/src/any/gen/traits/mod.rs
- nutype_macros/src/common/gen/traits.rs
- nutype_macros/src/float/gen/traits/mod.rs
- nutype_macros/src/integer/gen/traits/mod.rs
- nutype_macros/src/string/gen/traits/mod.rs
- test_suite/tests/any.rs
Fixes https://github.com/greyblake/nutype/issues/137
> Derive AsRef on newtypes with generics

- README.md
- dummy/src/main.rs
- examples/any_generics/src/main.rs
- nutype_macros/src/common/gen/mod.rs
- nutype_macros/src/common/gen/traits.rs
- test_suite/tests/any.rs
Fixes https://github.com/greyblake/nutype/issues/142
> Start working on trait boundaries for generics

- .github/workflows/ci.yml
- Justfile
- dummy/src/main.rs
- nutype_macros/src/any/gen/traits/arbitrary.rs
- nutype_macros/src/any/gen/traits/mod.rs
- nutype_macros/src/common/gen/mod.rs
- nutype_macros/src/common/gen/traits.rs
- test_suite/Cargo.toml
- test_suite/tests/any.rs
Closes https://github.com/greyblake/nutype/issues/140
> Implement support of derive(Arbitrary) for generic newtypes

- nutype_macros/src/any/gen/mod.rs
- nutype_macros/src/any/gen/traits/mod.rs
- nutype_macros/src/common/gen/mod.rs
- nutype_macros/src/common/gen/tests.rs
- nutype_macros/src/common/gen/traits.rs
- nutype_macros/src/float/gen/mod.rs
- nutype_macros/src/float/gen/traits/mod.rs
- nutype_macros/src/integer/gen/mod.rs
- nutype_macros/src/integer/gen/traits/mod.rs
- nutype_macros/src/string/gen/mod.rs
- nutype_macros/src/string/gen/traits/mod.rs
- test_suite/tests/any.rs
Addresses https://github.com/greyblake/nutype/issues/139
> Support derive(Default) for generic types

- nutype_macros/src/any/validate.rs
- nutype_macros/src/common/validate.rs
- nutype_macros/src/float/validate.rs
- nutype_macros/src/integer/validate.rs
- nutype_macros/src/string/validate.rs
- test_suite/tests/ui/any/derive/from_xor_try_from.rs
- test_suite/tests/ui/any/derive/from_xor_try_from.stderr
- test_suite/tests/ui/float/derive/from_xor_try_from.rs
- test_suite/tests/ui/float/derive/from_xor_try_from.stderr
- test_suite/tests/ui/integer/derive/from_xor_try_from.rs
- test_suite/tests/ui/integer/derive/from_xor_try_from.stderr
- test_suite/tests/ui/string/derive/from_xor_try_from.rs
- test_suite/tests/ui/string/derive/from_xor_try_from.stderr
Fixes https://github.com/greyblake/nutype/issues/147
> Better error message on attempt to derive both From and TryFrom

- README.md
- examples/string_regex_email/Cargo.toml
- examples/string_regex_email/src/main.rs
- nutype/src/lib.rs
- test_suite/tests/string.rs
This would need an MSRV of 1.80.0 so it might have to wait a bit.
Sorry for the formatting changes, if you'd consider merging this I'm happy to revert those.
EDIT: it's also fine to only use the docs + test (as they already work perfectly)
> Use LazyLock over lazy_static

- .github/workflows/ci.yml
- Justfile
Fixes https://github.com/greyblake/nutype/issues/169
> Fix doc tests

- README.md
- nutype/src/lib.rs
Following up https://github.com/greyblake/nutype/pull/198
> Add more docs on AsRef

- nutype_macros/src/common/gen/traits.rs
> Do not use alloc-dependent format! in serde expansion

- examples/no_std_example/Cargo.lock
- examples/no_std_example/Cargo.toml
- examples/no_std_example/src/main.rs
Fixes https://github.com/greyblake/nutype/issues/207
Addition to https://github.com/greyblake/nutype/pull/208
> Add a test to ensure Deserialize can be derived in no_std env
